FROM nvcr.io/nvidia/l4t-base:r35.4.1

# Directorio de trabajo
WORKDIR /app

# Instala librerías del sistema necesarias para visión
RUN apt-get update && apt-get install -y \
    python3-pip \
    python3-dev \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

# Alias python3 → python
RUN ln -sf python3 /usr/bin/python

# Instalar pip requirements
COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

# Copiar código al contenedor
COPY . .

# Para que los prints se vean en tiempo real
ENV PYTHONUNBUFFERED=1

# Ejecutar el script
CMD ["python", "src/modelIRL.py"]
