path: vision/model          # Root to the dataset
train: dataset/train         # Root to training images
val: dataset/val             # Root to validation images

#Classes
names:
  0: tree
  1: overmature
  2: mature
